### PR TITLE
Upgrade spring boot and java version

### PR DESCRIPTION
**Pull request by mirkoperillo**
Thank you @bfwg for this useful project starter.
This is my open source giving back.

Upgrade to spring boot 2.4.4 and Java 14

### CODE REVIEW

**Comment by bfwg** [comment]
Hi @mirkoperillo ,the change look but. My only thing is that the Travis build is failing. You might need to update the .travis. Thanks.

**Comment by mirkoperillo** [comment]
@bfwg done

**Comment by mirkoperillo** [comment]
Hi @bfwg do you think the PR can be considered completed and can be merged ?
I'm available if something is missing

**Comment by bfwg** [comment]
Totally, thanks for the reminder and welcome to the contributor team!

**Pull request merged**
